project: 
  type: website
  output-dir: docs

format: 
  html:
    fig-format: png
    
website:
  title: "Josh Medrano, Ph.D., Postdoctoral Scholar"
  google-analytics: "G-WY0TP47DPN"
  page-navigation: true
  navbar:
    title: "Josh Medrano, Ph.D."
    search: false
    pinned: true
    collapse: true
    right:
    - text: About
      href: index.qmd
    - text: CV
      href: about.qmd
    - text: Research
      href: research.qmd
    # - text: Science Communication
    #    menu:
    #      - href: publications.qmd
    #        text: Publications
    #      - href: presentations.qmd
    #        text: Presentations
    # - href: thoughts.qmd
    #  text: Thoughts

title-block-banner: false
title-block-banner-color: black

theme:
  - simplex
  - custom.scss

