---
title: "CV Overview"
format: html
editor: visual
---
### CV
:::{.column-page}
<iframe src="https://drive.google.com/file/d/1YNGtZyEai080zCla3GMF0QzjVQjNL7iK/preview" width="100%" height="600" allow="autoplay"></iframe>
:::

### Education

-   2019-2023 - Ph.D. in Human Development, University of Maryland, College Park
-   2018-2019 - M.Ed. in Educational Psychology, University of Virginia
-   2013-2016 - B.A. in Psychology, The Ohio State University

### Statistics Training

-   Univariate and multivariate statistics
-   General linear models, including linear, logistic, and quintile regressions
-   Exploratory latent and composite variable methods including cluster analyses
-   Structural equation modeling, including path analyses
-   Meta-analysis (2024 Modern Meta-Analysis Research Institute attendee)
-   Causal inference

### Programming Skills

-   Statistical analysis: R, SPSS, STATA, & SQL
-   Data visualization: ggplot, R Markdown/Quarto
-   Experiment development: PsychoPy, OpenSesame, MATLAB, Python, and EyeLink
-   Online experiment & survey development: Gorilla Experiment Builder and Qualtrics
-   Other programming: HTML, CSS, JavaScript, and Python

### Teaching Experience

-   Main Instructor for Research Methods in Human Development (40 undergraduate students, Spring 2023, UMD)
-   Graduate Teaching Assistant for Research Methods in Human Development (2 sections, 80 undergraduate students, Fall 2022, UMD)
-   Guest Lecturer for one section of Human Development Across the Lifespan (40 students, Fall 2021, UMD); Children's Thinking (40 students, Fall 2023, Kent State); Child Psychology (145 students, Spring 2024, Kent State)

### Outreach Experience

-   Virginia Discovery Museum, Charlottesville, VA, 2018-2019
-   The [Language Pod](https://u.osu.edu/thebln/language-pod/){target="_blank"} at the Center of Science and Industry (COSI), Columbus, OH, 2014
    -   Helped design a [demo](https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/4/44077/files/2017/03/TRICK-SENTENCES-DEMO-1mj2dhj.pdf){target="_blank"} of the Moses Illusion, illustrating top-down effects in sentence processing

<center><a href="https://drive.google.com/file/d/1YNGtZyEai080zCla3GMF0QzjVQjNL7iK/view?usp=sharing" target="_blank"><button type="button" class="btn btn-info">Download my full CV</button></a></center>

## Fun Facts

You can see young Josh [here](me-child.jpg). I value work-life balance. In my free time, I like to travel, be active, cook and eat dishes from different cuisines, and sing karaoke or in a [choir](https://www.youtube.com/watch?v=HhuiotKB43s).
