---
title: "josh medrano | ph.d. candidate"
format: html
editor: visual
---

Welcome!

Hello! I am a Postdoctoral Scholar in the Department of Psychological Sciences at Kent State University, working with [Dr. Dana Miller-Cotto](https://www.danamillercotto.com/). I received my Ph.D. in [Human Development](https://education.umd.edu/human-development-program) at [University of Maryland](https://umd.edu/), where I was advised by [Dr. Richard Prather](https://pratherlab.org/). 

In my research, I examine how domain-general skills, such as executive functions and spatial skills, contribute to math and science performance. I also aim to understand mechanisms of learning by integrating research from areas of developmental, cognitive, and educational psychology. Such research is important because early STEM skills affect later academic achievement, career, and daily life.

For more information, you can see my CV [here](https://drive.google.com/file/d/1WtSW1zbjm3Gc_OumLx3wE9QoNjC-UpRZ/view?usp=share_link).

You can also email me at [jmedran5\@kent.edu](mailto:jmedran5@kent.edu).

You can see my publication on [Google Scholar](https://scholar.google.com/citations?user=IrZrHOQAAAAJ&hl=en).
